version: '2'
services:
  web:
    image: odoo:12.0
    container_name: odoo
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.odoo-https.redirectscheme.scheme=https"
      - "traefik.http.routers.odoo-http.entrypoints=web"
      - "traefik.http.routers.odoo-http.rule=Host(`${HOSTNAME}`)"
      - "traefik.http.routers.odoo-http.middlewares=odoo-https@docker"
      - "traefik.http.routers.odoo.entrypoints=websecure"
      - "traefik.http.routers.odoo.rule=Host(`${HOSTNAME}`)"
      - "traefik.http.routers.odoo.tls=true"
      - "traefik.http.routers.odoo.tls.certresolver=${RESOLVER}"
      - "traefik.http.services.odoo.loadbalancer.server.port=${SERVER_PORT}"
    depends_on:
      - db
    # ports:
    #   - "8069:8069"
  db:
    image: postgres:10
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - /srv/odoo/postgres:/var/lib/postgresql/data/pgdata

networks:
  default:
    external:
        name: traefik_default