---
version: "2.1"
services:
  duplicati:
    image: linuxserver/duplicati
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.duplicati-https.redirectscheme.scheme=https"
      - "traefik.http.routers.duplicati-http.entrypoints=web"
      - "traefik.http.routers.duplicati-http.rule=Host(`${HOSTNAME}`)"
      - "traefik.http.routers.duplicati-http.middlewares=duplicati-https@docker"
      - "traefik.http.routers.duplicati.entrypoints=websecure"
      - "traefik.http.routers.duplicati.rule=Host(`${HOSTNAME}`)"
      - "traefik.http.routers.duplicati.tls=true"
      - "traefik.http.routers.duplicati.tls.certresolver=${RESOLVER}"
      - "traefik.http.services.duplicati.loadbalancer.server.port=${SERVER_PORT}"
    container_name: duplicati
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Americas/New_York
      - CLI_ARGS= #optional
    volumes:
      - ../../data/volumes/duplicati/config:/config
      - ../../:/backups
      - ../../backups:/source
    # ports:
    #   - 8200:8200
    restart: unless-stopped
networks:
  default:
    external:
       name: traefik_default
