version: "2.1"
services:
  wikijs:
    image: linuxserver/wikijs
    container_name: wikijs
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.wikijs-https.redirectscheme.scheme=https"
      - "traefik.http.routers.wikijs-http.entrypoints=web"
      - "traefik.http.routers.wikijs-http.rule=Host(`${HOSTNAME}`)"
      - "traefik.http.routers.wikijs-http.middlewares=wikijs-https@docker"
      - "traefik.http.routers.wikijs.entrypoints=websecure"
      - "traefik.http.routers.wikijs.rule=Host(`${HOSTNAME}`)"
      - "traefik.http.routers.wikijs.tls=true"
      - "traefik.http.routers.wikijs.tls.certresolver=${RESOLVER}"
      - "traefik.http.services.wikijs.loadbalancer.server.port=${SERVER_PORT}"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /srv/wikijs/config:/config
      - /srv/wikijs/data:/data

networks:
  default:
    external:
      name: traefik_default