version: '3'
services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.gitlab-https.redirectscheme.scheme=https"
      - "traefik.http.routers.gitlab-http.entrypoints=web"
      - "traefik.http.routers.gitlab-http.rule=Host(`${HOSTNAME}`)"
      - "traefik.http.routers.gitlab-http.middlewares=gitlab-https@docker"
      - "traefik.http.routers.gitlab.entrypoints=websecure"
      - "traefik.http.routers.gitlab.rule=Host(`${HOSTNAME}`)"
      - "traefik.http.routers.gitlab.tls=true"
      - "traefik.http.routers.gitlab.tls.certresolver=${RESOLVER}"
      - "traefik.http.services.gitlab.loadbalancer.server.port=${SERVER_PORT}"
    container_name: "gitlab"
    restart: always
    hostname: 'localhost'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url '${HOSTNAME}'
        unicorn['worker_timeout'] = 120
        unicorn['worker_processes'] = 2
    ports:
      - 80:80
      - 443:443
      - 22:22
    volumes:
      - ./gitlab/config:/etc/gitlab
      - ./gitlab/logs:/var/log/gitlab
      - ./gitlab/data:/var/opt/gitlab 
  networks:
    default:
      external:
          name: gitlab_default
