version: "2"
services: 
  portainer:
    image: portainer/portainer
    container_name: portainer
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.portainer-https.redirectscheme.scheme=https"
      - "traefik.http.routers.portainer-http.entrypoints=web"
      - "traefik.http.routers.portainer-http.rule=Host(`${HOSTNAME}`)"
      - "traefik.http.routers.portainer-http.middlewares=portainer-https@docker"
      - "traefik.http.routers.portainer.entrypoints=websecure"
      - "traefik.http.routers.portainer.rule=Host(`${HOSTNAME}`)"
      - "traefik.http.routers.portainer.tls=true"
      - "traefik.http.routers.portainer.tls.certresolver=${RESOLVER}"
      - "traefik.http.services.portainer.loadbalancer.server.port=${SERVER_PORT}"
      #- "traefik.docker.network=degoogle_default"
    environment:
      - UID=${UID}
      - GID=${GID}
      - TZ=${TZ}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /srv/portainer/data:/data
networks:
  default:
    external:
        name: traefik_default

# networks:
#   default:
#     external:
#       name: degoogle_default

