version: "3.3"

networks:
  default:
    driver: bridge
  traefik:
    internal: true

secrets:
  cf_api_email:
    file: "./secrets/cf_api_email.secret"
  cf_api_key:
    file: "./secrets/cf_api_key.secret"

services:
  dockerproxy:
    environment:
      CONTAINERS: 1
    image: tecnativa/docker-socket-proxy
    networks:
      - traefik
    ports:
      - 2375
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

  traefik:
    depends_on:
      - dockerproxy
    image: "traefik:v2.1"
    container_name: "traefik"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.dnschallenge=true"
      - "--certificatesresolvers.myresolver.acme.dnschallenge.provider=cloudflare"
      - "--certificatesresolvers.myresolver.acme.email=${EMAIL}"
      - "--certificatesresolvers.myresolver.acme.storage=/acme.json"
      - "--providers.docker.endpoint=tcp://dockerproxy:2375"
      # Disable SSL verification on backend
      # - "--serverstransport.insecureskipverify=true"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    restart: always
    networks:
      - default
      - traefik
    secrets:
      - "cf_api_email"
      - "cf_api_key"
    environment:
      - "CF_API_EMAIL_FILE=/run/secrets/cf_api_email"
      - "CF_API_KEY_FILE=/run/secrets/cf_api_key"
    volumes:
      - ./acme.json:/acme.json
      - ./tmp:/tmp