---
version: "3"
services:
  code-server:
    image: linuxserver/code-server
    container_name: code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Americas/New_York
      - PASSWORD=password #optional
      - SUDO_PASSWORD=password #optional
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.codeserver-https.redirectscheme.scheme=https"
      - "traefik.http.routers.codeserver-http.entrypoints=web"
      - "traefik.http.routers.codeserver-http.rule=Host(`codeserver.docker.guru`)"
      - "traefik.http.routers.codeserver-http.middlewares=codeserver-https@docker"
      - "traefik.http.routers.codeserver.entrypoints=websecure"
      - "traefik.http.routers.codeserver.rule=Host(`codeserver.docker.guru`)"
      - "traefik.http.routers.codeserver.tls=true"
      - "traefik.http.routers.codeserver.tls.certresolver=myresolver"
      - "traefik.http.services.codeserver.loadbalancer.server.port=8443"
    volumes:
      - ../../data/volumes/codeserver/config:/config
      - ~/degoogle:/config/workspace
    restart: unless-stopped
networks:
  default:
    external:
      name: traefik_default