version: "3"
services:
  code-server:
    image: linuxserver/code-server
    container_name: code-server
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.codeserver-https.redirectscheme.scheme=https"
      - "traefik.http.routers.codeserver-http.entrypoints=web"
      - "traefik.http.routers.codeserver-http.rule=Host(`${HOSTNAME}`)"
      - "traefik.http.routers.codeserver-http.middlewares=codeserver-https@docker"
      - "traefik.http.routers.codeserver.entrypoints=websecure"
      - "traefik.http.routers.codeserver.rule=Host(`${HOSTNAME}`)"
      - "traefik.http.routers.codeserver.tls=true"
      - "traefik.http.routers.codeserver.tls.certresolver=${RESOLVER}"
      - "traefik.http.services.codeserver.loadbalancer.server.port=${SERVER_PORT}"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - PASSWORD=${PASSWORD} #optional
      - SUDO_PASSWORD=${SUDO_PASSWORD} #optional
    volumes:
      - /srv/codeserver/config:/config
      - ~/openwfh-docker-compose:/config/workspace
networks:
  default:
    external:
      name: traefik_default