version: '2'

services:
  taiga:
    image: benhutchins/taiga
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.taiga-https.redirectscheme.scheme=https"
      - "traefik.http.routers.taiga-http.entrypoints=web"
      - "traefik.http.routers.taiga-http.rule=Host(`${HOSTNAME}`)"
      - "traefik.http.routers.taiga-http.middlewares=taiga-https@docker"
      - "traefik.http.routers.taiga.entrypoints=websecure"
      - "traefik.http.routers.taiga.rule=Host(`${HOSTNAME}`)"
      - "traefik.http.routers.taiga.tls=true"
      - "traefik.http.routers.taiga.tls.certresolver=${RESOLVER}"
      - "traefik.http.services.taiga.loadbalancer.server.port=${SERVER_PORT}"
    container_name: taiga
    ports:
      - 80:80
      # - 443:443 # To enable SSL, uncomment this line
    depends_on:
      - postgres
    volumes:
      # I recommend specifying a volume that maps to taiga's media,
      # this way uploaded files are not lost during upgrades of the taiga image
      - ./media:/usr/src/taiga-back/media

      # If you'd like to store the configuration outside of the container,
      # uncomment this volume. This allows for easy changes to the configuration.
      # - ./conf/taiga:/taiga

      # - ./ssl.crt:/etc/nginx/ssl/ssl.crt:ro # To enable SSL, uncomment this line
      # - ./ssl.key:/etc/nginx/ssl/ssl.key:ro # To enable SSL, uncomment this line
    environment:
      # Your hostname (REQUIRED)
      TAIGA_HOSTNAME: localhost

      # Database settings
      # To use an external database, simply update these and remove the postgres
      # service from this docker-compose.yml file
      TAIGA_DB_NAME: taigadb
      TAIGA_DB_HOST: postgres
      TAIGA_DB_USER: postgres
      TAIGA_DB_PASSWORD: password
      TAIGA_SLEEP: 15 # when the db comes up from docker, it is usually too quick

      # TAIGA_SSL: True # To enable SSL, uncomment this line
      # TAIGA_SSL_BY_REVERSE_PROXY: True # To enable SSL, handling by a reverse proxy, uncomment this

      # To use an external SMTP for emails, fill in these values:
      # TAIGA_ENABLE_EMAIL: True
      # TAIGA_EMAIL_FROM: no-reply@taiga.mycompany.net
      # TAIGA_EMAIL_USE_TLS: True
      # TAIGA_EMAIL_HOST: smtp.google.com
      # TAIGA_EMAIL_PORT: 587
      # TAIGA_EMAIL_USER: me@gmail.com
      # TAIGA_EMAIL_PASS: super-secure-pass phrase thing!

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: taigadb
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
    ports:
      - 5432
    volumes:
      # this helps prevent your postgres data from deleted
      - ./pgdata:/var/lib/postgresql/data