version: '3'
services:
  nextcloud:
    image: nextcloud:18.0.4
    container_name: nextcloud
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.nextcloud-caldav.redirectregex.permanent=true"
      - "traefik.http.middlewares.nextcloud-caldav.redirectregex.regex=^https://(.*)/.well-known/(card|cal)dav"
      - "traefik.http.middlewares.nextcloud-caldav.redirectregex.replacement=https://$${1}/remote.php/dav/"
      - "traefik.http.middlewares.nextcloud-https.redirectscheme.scheme=https"
      - "traefik.http.routers.nextcloud-http.entrypoints=web"
      - "traefik.http.routers.nextcloud-http.rule=Host(`${HOSTNAME}`)"
      - "traefik.http.routers.nextcloud-http.middlewares=nextcloud-https@docker"
      - "traefik.http.routers.nextcloud.entrypoints=websecure"
      - "traefik.http.routers.nextcloud.rule=Host(`${HOSTNAME}`)"
      - "traefik.http.routers.nextcloud.middlewares=nextcloud-caldav@docker"
      - "traefik.http.routers.nextcloud.tls=true"
      - "traefik.http.routers.nextcloud.tls.certresolver=${RESOLVER}"
    depends_on:
      - nextcloud-db           # If using MySQL
      - redis                  # If using Redis
    environment:
      - UID=${UID}
      - GID=${GID}
      - UPLOAD_MAX_SIZE=${UPLOAD_MAX_SIZE}
      - APC_SHM_SIZE=${APC_SHM_SIZE}
      - OPCACHE_MEM_SIZE=${OPCACHE_MEM_SIZE}
      - CRON_PERIOD=${CRON_PERIOD}
      - TZ=${TZ}
      - DOMAIN=${HOSTNAME}
      - DB_TYPE=${DB_TYPE}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
    volumes:
      - /srv/nextcloud/data:/var/www/html
      - /srv/nextcloud/config:/var/www/html/config
      - /srv/nextcloud/apps:/var/www/html/custom_apps
      - /srv/nextcloud/themes:/var/www/html/themes/custom_theme
    networks:
      - default

  # If using MySQL
  nextcloud-db:
    image: mariadb
    container_name: nextcloud-db
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - /srv/nextcloud/mariadb:/var/lib/mysql
    networks:
      - default
    
  # If using Redis
  redis:
    image: redis:alpine
    container_name: redis
    volumes:
      - /srv/nextcloud/redis:/data
    networks:
      - default

  nextcloud-db-backup:
    container_name: nextcloud-db-backup
    image: tiredofit/db-backup
    links:
      - nextcloud-db
    volumes:
      - /srv/db_backups/nextcloud:/backup
      - /srv/db_backups/script/post-script.sh:/assets/custom-scripts/post-script.sh
    environment:
      - DB_TYPE=${DB_TYPE}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${MYSQL_DATABASE}
      - DB_USER=${MYSQL_USER}
      - DB_PASS=${MYSQL_ROOT_PASSWORD}
      - DB_DUMP_FREQ=1440
      - DB_DUMP_BEGIN=0000
      - DB_CLEANUP_TIME=8640
      - MD5=TRUE
      - COMPRESSION=GZ
      - SPLIT_DB=FALSE
    restart: always
    networks:
      - default

networks:
  default:
    external: 
      name: traefik_default
  # nextcloud:
  #   external: false