version: '3'
services:
  nextcloud:
    image: nextcloud:18.0.4
    container_name: nextcloud
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.nextcloud-caldav.redirectregex.permanent=true"
      - "traefik.http.middlewares.nextcloud-caldav.redirectregex.regex=^https://(.*)/.well-known/(card|cal)dav"
      - "traefik.http.middlewares.nextcloud-caldav.redirectregex.replacement=https://$${1}/remote.php/dav/"
      - "traefik.http.middlewares.nextcloud-https.redirectscheme.scheme=https"
      - "traefik.http.routers.nextcloud-http.entrypoints=web"
      - "traefik.http.routers.nextcloud-http.rule=Host(`${HOSTNAME}`)"
      - "traefik.http.routers.nextcloud-http.middlewares=nextcloud-https@docker"
      - "traefik.http.routers.nextcloud.entrypoints=websecure"
      - "traefik.http.routers.nextcloud.rule=Host(`${HOSTNAME}`)"
      - "traefik.http.routers.nextcloud.middlewares=nextcloud-caldav@docker"
      - "traefik.http.routers.nextcloud.tls=true"
      - "traefik.http.routers.nextcloud.tls.certresolver=${RESOLVER}"
    depends_on:
      - nextcloud-db           # If using MySQL
      - redis                  # If using Redis
    environment:
      - UID=${UID}
      - GID=${GID}
      - UPLOAD_MAX_SIZE=${UPLOAD_MAX_SIZE}
      - APC_SHM_SIZE=${APC_SHM_SIZE}
      - OPCACHE_MEM_SIZE=${OPCACHE_MEM_SIZE}
      - CRON_PERIOD=${CRON_PERIOD}
      - TZ=${TZ}
      - DOMAIN=${HOSTNAME}
      - DB_TYPE=${DB_TYPE}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
    volumes:
      - /srv/nextcloud/data:/data
      - /srv/nextcloud/config:/config
      - /srv/nextcloud/apps:/apps2
      - /srv/nextcloud/themes:/nextcloud/themes
    networks:
      - default

  # If using MySQL
  nextcloud-db:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - /srv/nextcloud/mariadb:/var/lib/mysql
    networks:
      - default
    
  # If using Redis
  redis:
    image: redis:alpine
    container_name: redis
    volumes:
      - /srv/nextcloud/redis:/data
    networks:
      - default

networks:
  default:
    external: 
      name: traefik_default
  # nextcloud:
  #   external: false